### ISSUE TITLE
PEP 2.0.0 is outdated

### ISSUE THREAD

**Issue by nsheff** [databio/schema.databio.org#3]
the pep schema lacks the latest changes to the spec, like `project_modifiers`.

**Comment by stolarczyk** [comment]
right, I'll add the new sections.

what's more, we the schema in two spots in this repository. I've been using and editing this one: https://github.com/databio/schema.databio.org/blob/master/pep/2.0.0.yaml

Are you aware of anything using the other one? Is it safe to delete it?

**Comment by nsheff** [comment]
I think you can delete it.
