### ISSUE TITLE
Improvement suggestions for user interface

### ISSUE THREAD

**Issue by nsheff** [databio/schema.databio.org#5]
Right now the interface is fine, but it's not going to scale when we get more schemas, because it's a one-page that just shows everything on the same page. Here are some suggesting improvements:

## 1. Splash pages for individual schemas

Right now, there's a single page, and all schemas are listed on that page. Each schema should have its own page. This can just be accomplished via React. If you hit `schema.databio.org/view/pipelines/bedbuncher` then, instead of showing a list of all schemas, it shows a splash page for the single schema.

The one-schema page should show:
- all the details currently shown in the list view
- the schema itself, in nice format.
- download link to download the schema as a file

## 2. Splash page for namespaces

Let's make the current "list everything" view instead a namespace-specific view that only lists the schemas for a given namespace. at `schema.databio.org/view/pipelines`, you'd see all the schemas under pipelines

## 3. Revamp list view

Finally, given the above changes, the default view at `schema.databio.org`, which is currently a list of details of all schemas, should become simpler. I think it should provide links to namespaces. Maybe it's an auto-populating text box for namespaces, kind of analogous to how pephub allows you to select a schema.

**Comment by nsheff** [comment]
Once this is done, the link to the schema from pephub should be changed. Right now, it links to the schema itself; instead, it should link to the schema's splash page.

**Comment by ayobi** [comment]
I see, sounds good, this is progressing well, should have something soon

**Comment by ayobi** [comment]
This is complete and live https://schema.databio.org/ 
Schema tag on PEPhub has been updated to route to a schemas splash page.
